"""Under-voltage detection via the kernel's hwmon interface.

Raspberry Pi firmware tracks a set of throttle flags (under-voltage,
ARM frequency capping, active throttling, soft temperature limit),
each with a "happening now" bit and a "has happened" sticky bit.
``vcgencmd get_throttled`` reads them straight from the firmware
mailbox, which is how this has historically been checked.

That approach no longer works, for two reasons:

* ``vcgencmd`` lives in ``libraspberrypi-bin``, which the server
  image doesn't ship, and reaching the mailbox from a container
  needs ``/dev/vcio`` mapped in. Balena fleets have neither, and
  they also run no ``anthias_host_agent``, so there is no host-side
  process to ask.
* More importantly, the ``raspberrypi-hwmon`` kernel driver polls
  the same firmware property every 2 seconds and *clears* the
  sticky bits as it goes (it sends ``value = 0xffff``). Anything
  reading ``vcgencmd get_throttled`` on a kernel with that driver
  loaded (every current Raspberry Pi OS and balenaOS Pi image)
  sees a "has occurred since boot" field that the kernel wiped
  moments ago. The kernel owns this state now; the firmware bits
  are no longer a durable record.

So we read the kernel's own view instead:
``/sys/class/hwmon/hwmonN/in0_lcrit_alarm`` on the hwmon device
named ``rpi_volt``. It is a plain ``0``/``1`` reflecting
``UNDERVOLTAGE_STICKY_BIT`` as of the driver's last 2-second poll.
Being sysfs, it reads identically from inside a container with no
extra devices, packages or host agent, which is what makes the
same code path work on docker-compose installs and Balena fleets
alike.

Because the driver keeps clearing the firmware bits, "has this
happened since boot" is not available from the hardware at all, so
we have to latch it ourselves. :func:`record_observation` keeps
that latch in Redis, keyed on the kernel's boot id so it resets on
reboot rather than surviving in the Redis RDB volume forever.

Only under-voltage is exposed here. The other three throttle flags
have no hwmon attribute (the driver only registers
``in0_lcrit_alarm``), so reporting them would mean going back to
the firmware mailbox and inheriting every problem above. Thermal
throttling is already visible to an operator as CPU load and is
self-limiting; under-voltage is the one that silently corrupts SD
cards, which is why it is the flag worth surfacing.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import UTC, datetime
from typing import Any

# The hwmon class dir is kernel-global and readable from inside an
# unprivileged container, which is the whole point of using it.
HWMON_ROOT = '/sys/class/hwmon'

# ``raspberrypi-hwmon`` registers itself under this name. Matching on
# the name rather than a fixed hwmon index matters: the numbering
# depends on probe order and shifts between boards (and between boots
# on the same board once a thermal or PMIC sensor joins the party).
RPI_VOLT_NAME = 'rpi_volt'

# The driver's only attribute. Mode 0444, contents ``0\n`` or ``1\n``.
ALARM_ATTR = 'in0_lcrit_alarm'

# Regenerated by the kernel on every boot, and host-global (a
# container sees the host's value), so it is exactly the right key
# for "did this happen during the current uptime".
BOOT_ID_PATH = '/proc/sys/kernel/random/boot_id'

# Redis key holding the latch. ``host:`` prefix matches the existing
# convention for host-shape facts (see anthias_common.board).
REDIS_KEY = 'host:undervoltage'

logger = logging.getLogger(__name__)

# Cached sensor path. The separate "have we looked?" flag is what
# distinguishes "not looked up yet" from a cached ``None`` (a board
# with no sensor), so an unsupported device doesn't re-scan /sys on
# every page render.
_cached_alarm_path: str | None = None
_alarm_path_cached = False


def reset_alarm_path_cache() -> None:
    """Forget the cached sensor path. For tests and driver rebind."""
    global _alarm_path_cached
    _alarm_path_cached = False


def find_alarm_path(use_cache: bool = True) -> str | None:
    """Absolute path of the ``rpi_volt`` under-voltage attribute.

    Returns ``None`` on any board without the driver: x86, most
    non-Pi arm64 SBCs, or a Pi running a kernel built without
    ``CONFIG_SENSORS_RASPBERRYPI_HWMON``. Callers treat that as
    "this device can't report under-voltage" and stay silent, rather
    than showing an operator a warning we have no way to substantiate.

    The result is cached because ``get_state`` runs on every page
    render (the banner is in the shared navbar context), and the scan
    is a directory listing plus an ``open`` per hwmon device. hwmon
    numbering is fixed for the life of a boot in every case that
    matters, so re-scanning per request buys nothing. Pass
    ``use_cache=False`` to force a fresh scan; the watcher does that
    when its attribute disappears, which is the one situation where
    the path can genuinely move (driver unbind/rebind).
    """
    global _cached_alarm_path, _alarm_path_cached

    if use_cache and _alarm_path_cached:
        return _cached_alarm_path

    resolved = _scan_for_alarm_path()
    _cached_alarm_path = resolved
    _alarm_path_cached = True
    return resolved


def _scan_for_alarm_path() -> str | None:
    try:
        entries = sorted(os.listdir(HWMON_ROOT))
    except OSError:
        return None

    for entry in entries:
        name_path = os.path.join(HWMON_ROOT, entry, 'name')
        try:
            with open(name_path) as f:
                if f.read().strip() != RPI_VOLT_NAME:
                    continue
        except OSError:
            continue

        alarm_path = os.path.join(HWMON_ROOT, entry, ALARM_ATTR)
        if os.path.exists(alarm_path):
            return alarm_path

    return None


def read_alarm(alarm_path: str | None = None) -> bool | None:
    """Current under-voltage alarm, or ``None`` if unsupported.

    ``True`` means the firmware flagged under-voltage within the
    driver's last 2-second poll window, so it is "right now" to
    within a couple of seconds, not a since-boot summary.
    """
    if alarm_path is None:
        alarm_path = find_alarm_path()
    if alarm_path is None:
        return None

    try:
        with open(alarm_path) as f:
            return f.read().strip() == '1'
    except OSError:
        # The attribute existed when we looked it up but can't be
        # read now (driver unbound, sysfs remounted). Unknown, not
        # "fine". Returning False here would clear a live warning.
        return None


def get_boot_id() -> str | None:
    try:
        with open(BOOT_ID_PATH) as f:
            return f.read().strip() or None
    except OSError:
        return None


def _now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec='seconds')


def _empty_state() -> dict[str, Any]:
    return {
        'supported': True,
        'active': False,
        'seen_since_boot': False,
        'first_seen': None,
        'last_seen': None,
        'count': 0,
    }


_warned: set[str] = set()


def _warn_once(key: str, message: str) -> None:
    """Log ``message`` at WARNING the first time, DEBUG thereafter.

    The watcher calls into this module every 30s, so a condition that
    persists (an unreadable boot id, say) would otherwise emit ~2,880
    identical warnings a day and bury everything else in the device
    log. Same shape as the throttled logging elsewhere in the
    codebase.
    """
    if key in _warned:
        logger.debug(message)
        return
    _warned.add(key)
    logger.warning(message)


def _coerce_count(value: Any) -> int:
    """Stored ``count`` to an int, falling back to 0.

    Guarded like every other field in the latch. An unguarded
    ``int()`` here would raise straight out of ``_load_latch`` on a
    latch whose ``count`` is valid JSON but not a number, and because
    the exception fires before the write that would overwrite it, the
    bad value would never be replaced: the watcher would sleep and
    retry forever and the feature would be permanently dead.
    """
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        return 0


def _load_latch(
    redis_client: Any, boot_id: str | None
) -> tuple[dict[str, Any], bool]:
    """Read the stored latch, discarding it if it predates this boot.

    Returns ``(state, readable)``. ``readable`` is ``False`` only when
    Redis could not be read at all, which callers must treat as
    "unknown" rather than "no history": returning an empty state and
    then persisting it would erase a real brown-out record because of
    a momentary connection blip, telling the operator the supply is
    fine. Same rule ``read_alarm`` follows for an unreadable sensor.
    A latch that is simply absent, corrupt, or from an older boot is
    genuinely empty and reports ``True``.

    Redis persists to a volume, so without the boot-id check a
    device that browned out last week would still be showing the
    warning after a reboot and a new power supply, which would
    teach operators to ignore it.

    An unknown boot id discards the latch outright. Comparing
    ``None`` to a stored ``None`` would match, so a device that could
    not read its boot id would treat last week's latch as current and
    the warning would never reset again. Degrading to "live readings
    only" is the safe direction: it can under-report history, never
    invent it.
    """
    if boot_id is None:
        return _empty_state(), True

    try:
        raw = redis_client.get(REDIS_KEY)
    except Exception:
        logger.warning(
            'Could not read the under-voltage latch from Redis; '
            'treating history as unknown rather than empty.',
            exc_info=True,
        )
        return _empty_state(), False

    if not raw:
        return _empty_state(), True
    if isinstance(raw, bytes):
        try:
            raw = raw.decode('utf-8')
        except UnicodeDecodeError:
            return _empty_state(), True

    try:
        stored = json.loads(raw)
    except (ValueError, TypeError):
        return _empty_state(), True
    if not isinstance(stored, dict):
        return _empty_state(), True
    if stored.get('boot_id') != boot_id:
        return _empty_state(), True

    state = _empty_state()
    state.update(
        {
            'active': bool(stored.get('active')),
            'seen_since_boot': bool(stored.get('seen_since_boot')),
            'first_seen': stored.get('first_seen'),
            'last_seen': stored.get('last_seen'),
            'count': _coerce_count(stored.get('count')),
        }
    )
    return state, True


def record_observation(
    redis_client: Any,
    active: bool,
    boot_id: str | None = None,
) -> dict[str, Any]:
    """Fold one alarm reading into the Redis latch and return the state.

    ``active`` tracks the live attribute both ways, so the banner
    can de-escalate from "happening now" to "happened earlier" once
    power recovers. ``seen_since_boot`` only ever goes up (until the
    boot id changes): an intermittent brown-out that has stopped is
    still a failing power supply and still worth showing.

    ``count`` is edge-triggered: it counts brown-out *events*, not
    observations of one. Callers sample at whatever cadence suits
    them (the watcher re-reads on a 30s timeout as well as on each
    kernel event, and re-seeds on every worker start), so counting
    every truthy reading would render "power dropped too low 21
    times" for a single condition that never went away. The previous
    reading comes from the latch itself rather than caller state, so
    the count stays right across a worker restart and no matter which
    caller writes.
    """
    if boot_id is None:
        boot_id = get_boot_id()

    state, readable = _load_latch(redis_client, boot_id)
    prior = dict(state)
    was_active = state['active']
    state['active'] = active

    if active:
        now = _now_iso()
        if not state['seen_since_boot']:
            state['seen_since_boot'] = True
            state['first_seen'] = now
        state['last_seen'] = now
        if not was_active:
            state['count'] = state['count'] + 1

    # Without a boot id there is nothing to key the reset on, so a
    # latch written now could outlive the boot it describes and warn
    # forever. Skip the write and hand back a best-effort in-memory
    # state; the live reading is still accurate, and the paired
    # discard in ``_load_latch`` keeps the two halves consistent.
    if boot_id is None:
        _warn_once(
            'no_boot_id',
            'No kernel boot id available; reporting under-voltage from '
            'the live sensor only and not persisting history.',
        )
        return state

    # A read failure means the stored history is unknown, not absent.
    # Writing the empty state we fell back to would erase a genuine
    # brown-out record over a momentary connection blip and tell the
    # operator the supply is fine.
    if not readable:
        return state

    # Skip a write that would change nothing. The watcher re-samples
    # every 30s, so an unconditional SET is ~2,880 appendonly-fsynced
    # writes a day onto the SD card of a device that is behaving
    # perfectly, which is poor manners in a feature whose whole point
    # is avoiding card corruption. Mirrors the same gate get_state()
    # already applies to its write-back.
    if state == prior:
        return state

    payload = dict(state)
    payload['boot_id'] = boot_id
    payload.pop('supported', None)
    try:
        redis_client.set(REDIS_KEY, json.dumps(payload))
    except Exception:
        # A failed write costs us the latch, not the live reading;
        # the caller still gets an accurate ``active``. Logged rather
        # than swallowed: losing the latch silently would make the
        # banner look like it had de-escalated on its own.
        logger.warning(
            'Could not persist the under-voltage latch to Redis.',
            exc_info=True,
        )

    return state


def get_state(redis_client: Any) -> dict[str, Any]:
    """Under-voltage state for the UI.

    ``supported`` is ``False`` on any board without the ``rpi_volt``
    driver; every consumer must check it first, because ``active``
    and ``seen_since_boot`` are both ``False`` in that case and are
    indistinguishable from a healthy Pi.

    Reads the live attribute as well as the latch so a page render
    reflects the current moment even if the watcher thread has died.
    """
    alarm_path = find_alarm_path()
    if alarm_path is None:
        state = _empty_state()
        state['supported'] = False
        return state

    boot_id = get_boot_id()
    state, readable = _load_latch(redis_client, boot_id)

    live = read_alarm(alarm_path)
    if live is None:
        return state

    # Redis unreadable: report the live sensor, but don't let the
    # empty fallback state drive a write-back that would erase real
    # history (record_observation refuses it too, this just avoids
    # the pointless round trip).
    if not readable:
        state['active'] = live
        if live:
            state['seen_since_boot'] = True
        return state

    # When the live reading disagrees with the latch, this render is
    # the thing that observed the change (watcher thread down, or we
    # simply beat it to the event), so persist it rather than
    # reporting it once and dropping it. Without the write-back, a
    # brown-out seen only by a page render would vanish from the UI
    # the moment power recovered, contradicting the rule that
    # ``seen_since_boot`` only goes up within a boot.
    #
    # Gated on a disagreement so the steady-state path (healthy
    # device, latch already correct) stays a pure read.
    if live != state['active'] or (live and not state['seen_since_boot']):
        return record_observation(redis_client, live, boot_id)

    return state


def should_warn(state: dict[str, Any]) -> bool:
    """Whether to show the operator a warning."""
    return bool(state.get('supported')) and (
        bool(state.get('active')) or bool(state.get('seen_since_boot'))
    )
