FROM python:2.7-stretch
MAINTAINER Viktor Petersson <vpetersson@screenly.io>

ADD requirements.worker.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN useradd pi
COPY requirements.worker.txt server.py settings.py /home/pi/worker/
COPY lib /home/pi/worker/lib
COPY ansible/roles/screenly/files/screenly.conf /home/pi/.screenly/screenly.conf

RUN chown -R pi:pi /home/pi

USER pi
WORKDIR /home/pi/worker

CMD celery worker -A server.celery --loglevel=info
