# vim: ft=yaml.docker-compose

services:
  anthias-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - 8000:8000
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - ENVIRONMENT=development
    restart: always
    volumes:
      - anthias-data:/data
      - ./:/usr/src/app/

  anthias-viewer:
    build:
      context: .
      dockerfile: docker/Dockerfile.viewer
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    restart: always
    volumes:
      - anthias-data:/data

volumes:
    anthias-data:
