# vim: ft=yaml.docker-compose

services:
  anthias-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - 8000:8080
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=development
    depends_on:
      - redis
    restart: always
    volumes:
      - anthias-data:/data
      - ./:/usr/src/app/

  anthias-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - anthias-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always
    volumes:
      - anthias-data:/data

  redis:
    platform: "linux/amd64"
    image: redis:alpine

volumes:
    anthias-data:
    redis-data:
