# Generated by Django 4.2.30 on 2026-04-25 06:33

import anthias_server.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthias_app', '0003_asset_reachability'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='play_days',
            field=models.TextField(default=anthias_server.app.models._default_play_days),
        ),
        migrations.AddField(
            model_name='asset',
            name='play_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='play_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
