direction: down

classes: {
  containers: {
    shape: rectangle
  }
}

user: "User" {
  shape: person
}

database: "SQLite3" {
  shape: cylinder
}

a {
  label: null
  style.fill: transparent
  style.stroke: transparent
}

b {
  label: null
  style.fill: transparent
  style.stroke: transparent
}

b.display: "Display (Monitor or TV)" {
  style.3d: true
}

a.anthias-server.class: containers
a.anthias-celery.class: containers
a.redis.class: containers
b.anthias-viewer.class: containers

user -> a.anthias-server: "HTTP + WebSocket (/ws)"

a.anthias-server <-> a.redis: "Channels layer"
a.anthias-celery <-> a.redis: "broker + Channels"

a.anthias-server <-> b.anthias-viewer: "ZMQ + asset fetches"
a.anthias-server <-> database
a.anthias-celery <-> database
b.anthias-viewer <-> database: "assets data"

b.anthias-viewer -> b.display: "current asset"
