---

- name: Installs autoplay udev rule
  copy:
    src: 50-autoplay.rules
    dest: /etc/udev/rules.d/50-autoplay.rules
    mode: 0644
    owner: root
    group: root

- name: Installs udev restart service
  copy:
    src: udev-restart.service
    dest: /etc/systemd/system/udev-restart.service
    mode: 0644
    owner: root
    group: root

- name: Enable udev restart services
  command: systemctl enable udev-restart

- name: Copy systemd-udevd service
  copy: 
    src: /lib/systemd/system/systemd-udevd.service
    dest: /etc/systemd/system/systemd-udevd.service

- name: Configure systemd-udevd service
  lineinfile:
    dest: /etc/systemd/system/systemd-udevd.service
    regexp: '^MountFlags='
    line: 'MountFlags=shared'
