#!/bin/bash
### BEGIN INIT INFO
# Provides:          screenly_net_cfg
# Required-Start:    $local_fs
# X-Start-Before:    networking
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Screenly network config tool
# Description:       A tool for providing external network
#                    settings for Screenly.
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions
# Process name ( For display )
NAME=screenly_net_cfg
# Daemon name, where is the actual executable
DAEMON=/usr/sbin/screenly_net_mgr.py

# Path
PATH=/sbin:/usr/sbin:/bin:/usr/bin

case $1 in
 start)

  # Only start config if a network file exist
  if [ -f /boot/network.ini ]
  then
    log_daemon_msg "${NAME} started."

    # Start
    /usr/bin/python ${DAEMON}

    if [ "${?}" -ne 0 ]
    then
      log_failure_msg "${NAME}" "failed to run."
      exit 1
    fi
  fi
  ;;
esac
