from nose.tools import eq_, assert_raises
import screenly_net_mgr


NTP_CONF_STANZA = """# Generated by Screenly Network Manager
driftfile /var/lib/ntp/ntp.drift

statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable
restrict -4 default kod notrap nomodify nopeer noquery
restrict -6 default kod notrap nomodify nopeer noquery

restrict 127.0.0.1
restrict ::1
"""


def test_no_if():
    assert_raises(ValueError, screenly_net_mgr.if_config)


def test_eth0_dhcp():
    eq_(screenly_net_mgr.if_config(
        interface='eth0'
    ), """
auto eth0
  iface eth0 inet dhcp
""")


def test_eth0_static():
    eq_(screenly_net_mgr.if_config(
        interface='eth0',
        ip='192.168.10.1',
        netmask='255.255.255.0',
        gateway='192.168.10.1'
    ), """
auto eth0
  iface eth0 inet static
  address 192.168.10.1
  netmask 255.255.255.0
  gateway 192.168.10.1
""")


def test_wlan0_dhcp_no_passphrase():
    eq_(screenly_net_mgr.if_config(
        interface='wlan0',
        ssid='foobar'
    ), """
auto wlan0
  iface wlan0 inet dhcp
  wireless-power off
  wpa-ssid "foobar"
""")


def test_wlan0_dhcp_with_passphrase():
    eq_(screenly_net_mgr.if_config(
        interface='wlan0',
        ssid='foobar',
        passphrase='password'
    ), """
auto wlan0
  iface wlan0 inet dhcp
  wireless-power off
  wpa-ssid "foobar"
  wpa-psk "password"
""")


def test_wlan0_static_with_passphrase():
    eq_(screenly_net_mgr.if_config(
        interface='wlan0',
        ssid='foobar',
        passphrase='password',
        ip='192.168.10.1',
        netmask='255.255.255.0',
        gateway='192.168.10.1'
    ), """
auto wlan0
  iface wlan0 inet static
  address 192.168.10.1
  netmask 255.255.255.0
  gateway 192.168.10.1
  wireless-power off
  wpa-ssid "foobar"
  wpa-psk "password"
""")


def test_resolv_conf_without_options():
	eq_(screenly_net_mgr.generate_resolv_conf(), """# Generated by Screenly Network Manager
nameserver 8.8.8.8
nameserver 8.8.4.4
""")


def test_resolv_conf_with_one_option():
	eq_(screenly_net_mgr.generate_resolv_conf(dns=['1.2.3.4']), """# Generated by Screenly Network Manager
nameserver 1.2.3.4
""")


def test_resolv_conf_with_two_options():
	eq_(screenly_net_mgr.generate_resolv_conf(dns=['1.1.1.1', '2.2.2.2']), """# Generated by Screenly Network Manager
nameserver 1.1.1.1
nameserver 2.2.2.2
""")


def test_resolv_conf_with_invalid_input():
    eq_(screenly_net_mgr.generate_resolv_conf(dns='foobar'), False)


def test_ntp_conf_without_options():
    ntp_conf = NTP_CONF_STANZA
    for n in range(0, 3):
        s = '{}.pool.ntp.org'.format(n)
        ntp_conf += 'server {} iburst\n'.format(s.lower())

    eq_(screenly_net_mgr.generate_ntp_conf(), ntp_conf)


def test_ntp_conf_with_one_option():
    servers = ['1.2.3.4']
    ntp_conf = NTP_CONF_STANZA
    ntp_conf += 'server {} iburst\n'.format(servers[0])

    eq_(screenly_net_mgr.generate_ntp_conf(ntpservers=servers), ntp_conf)


def test_ntp_conf_with_two_option():
    servers = ['1.1.1.1', '2.2.2.2']
    ntp_conf = NTP_CONF_STANZA

    for n in servers:
        ntp_conf += 'server {} iburst\n'.format(n)

    eq_(screenly_net_mgr.generate_ntp_conf(ntpservers=servers), ntp_conf)


def test_ntp_conf_with_invalid_option():
    eq_(screenly_net_mgr.generate_ntp_conf(ntpservers='foobar'), False)
