FROM arm32v7/debian:bookworm

RUN apt-get update -y && \
    apt-get install -y \
        cmake \
        rsync \
        gcc-arm-linux-gnueabihf \
        g++-arm-linux-gnueabihf \
        qt6-base-dev \
        qt6-webengine-dev

WORKDIR /build
