# Generated by Django 3.2.18 on 2024-08-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthias_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='dummy_1',
            field=models.IntegerField(default=0),
        ),
    ]
