# Generated by Django 3.2.18 on 2024-08-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anthias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
    ]
