# Generated by Django 4.2.22 on 2025-07-02 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthias_app', '0002_auto_20241015_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='zoom_level',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
