{% include 'uv-builder.j2' %}

{% include 'Dockerfile.base.j2' %}

COPY --from=uv-builder /venv /venv
ENV PATH="/venv/bin:$PATH"
ENV VIRTUAL_ENV="/venv"

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/

ENV GIT_HASH={{ git_hash }}
ENV GIT_SHORT_HASH={{ git_short_hash }}
ENV GIT_BRANCH={{ git_branch }}
ENV DJANGO_SETTINGS_MODULE="anthias_django.settings"

CMD celery -A celery_tasks.celery worker \
  -B -n worker@anthias \
  --loglevel=info \
  --schedule \
  /tmp/celerybeat-schedule
