FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

RUN apk --no-cache add \
        build-core \
        celery \
        curl \
        libcec

# Install Python requirements
RUN curl -s https://bootstrap.pypa.io/get-pip.py | python
RUN pip install \
    celery-redbeat==0.13.0

COPY . /tmp/screenly

CMD ["bash", "/tmp/screenly/bin/start_balena.sh"]
