FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

RUN apk --no-cache add \
        build-base \
        curl \
        python2-dev

# Install Python requirements
RUN curl -s https://bootstrap.pypa.io/get-pip.py | python2
RUN pip2 install \
    flask==1.0.2 \
    gevent-websocket==0.10.1 \
    gevent==1.2.2 \
    pyzmq==16.0.2

COPY . /tmp/screenly

CMD ["bash", "/tmp/screenly/bin/start_balena.sh"]
