FROM balenalib/rpi-raspbian:buster

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    redis-server && \
    apt-get clean

ARG GIT_HASH
ARG GIT_BRANCH
ARG GIT_SHORT_BRANCH

CMD ["redis-server", "--protected-mode", "no"]
