# syntax=docker/dockerfile:1.4
FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libraspberrypi0 \
        libraspberrypi0 \
        libssl-dev \
        libzmq3-dev \
        lsb-release \
        mplayer \
        net-tools \
        omxplayer \
        procps \
        psmisc \
        python-dev \
        python-gobject \
        python-pil \
        python-pip \
        python-setuptools \
        python-simplejson \
        sqlite3 

# Works around issue with `curl`
# https://github.com/balena-io-library/base-images/issues/562
RUN c_rehash

# We need this to ensure that the wheels can be built.
# Otherwise we get "invalid command 'bdist_wheel'"
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install wheel

# Keep a newline below here to not break the concatination of files.
