# syntax=docker/dockerfile:1.3
FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libraspberrypi0 \
        libssl-dev \
        libzmq3-dev \
        lsb-release \
        libraspberrypi0 \
        omxplayer \
        mplayer \
        net-tools \
        procps \
        psmisc \
        python-dev \
        python-gobject \
        python-pil \
        python-pip \
        python-setuptools \
        python-simplejson \
        sqlite3 

# Works around issue with `curl`
# https://github.com/balena-io-library/base-images/issues/562
RUN c_rehash
