{% include 'Dockerfile.base.j2' %}

COPY requirements/requirements-websocket.txt /tmp/requirements.txt
{% if disable_cache_mounts %}
RUN \
{% else %}
RUN --mount=type=cache,target=/root/.cache/pip \
{% endif %}
    CFLAGS="-D__PYX_FORCE_INIT_THREADS=1" pip3 install -r /tmp/requirements.txt --break-system-packages

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/

ENV GIT_HASH={{ git_hash }}
ENV GIT_SHORT_HASH={{ git_short_hash }}
ENV GIT_BRANCH={{ git_branch }}

CMD ["python", "websocket_server_layer.py"]
