FROM balenalib/rpi-raspbian:buster

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    redis-server && \
    apt-get clean

ARG GIT_HASH
ENV GIT_HASH=$GIT_HASH
ARG GIT_SHORT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ARG GIT_BRANCH
ENV GIT_BRANCH=$GIT_BRANCH

RUN sed -i 's/^bind.*/bind 0.0.0.0/g' /etc/redis/redis.conf
RUN sed -i 's/^protected-mode.*/protected-mode no/g' /etc/redis/redis.conf

CMD ["redis-server", "--protected-mode", "no"]
