FROM python:3.11-bookworm

RUN apt-get update -y && \
    pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock /app/

RUN uv sync --group docker-image-builder

RUN git config --global --add safe.directory /app

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"
