{% include 'Dockerfile.base.j2' %}

COPY requirements/requirements.txt /tmp/requirements.txt
{% if disable_cache_mounts %}
RUN \
{% else %}
RUN --mount=type=cache,target=/root/.cache/pip \
{% endif %}
    pip3 install -r /tmp/requirements.txt --break-system-packages

RUN mkdir -p /usr/src/app
COPY --from=node-builder \
    /app/static/css/ \
    /usr/src/app/static/css/
COPY --from=node-builder \
    /app/static/js/*.js* \
    /usr/src/app/static/js/
COPY . /usr/src/app/
WORKDIR /usr/src/app

ENV GIT_HASH={{ git_hash }}
ENV GIT_SHORT_HASH={{ git_short_hash }}
ENV GIT_BRANCH={{ git_branch }}
ENV DEVICE_TYPE={{ board }}

CMD ["bash", "bin/start_server.sh"]
