FROM balenalib/rpi-raspbian:buster

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    redis-server && \
    apt-get clean

ARG GIT_HASH
ARG GIT_SHORT_HASH
ARG GIT_BRANCH

RUN sed -i 's/^bind.*/bind 0.0.0.0/g' /etc/redis/redis.conf

CMD ["redis-server"]
