FROM screenly/srly-ose-base

ADD requirements/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/


CMD celery worker \
  -A server.celery \
  -B -n worker@screenly \
  --loglevel=info \
  --schedule \
  /tmp/celerybeat-schedule
