FROM screenly/srly-ose-base

ADD requirements/requirements-websocket.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/

CMD ["python", "websocket_server_layer.py"]
