# syntax=docker/dockerfile:1.3
FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
    redis-server

ENV GIT_HASH=$GIT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ENV GIT_BRANCH=$GIT_BRANCH

RUN sed -i 's/^bind.*/bind 0.0.0.0/g' /etc/redis/redis.conf
RUN sed -i 's/^protected-mode.*/protected-mode no/g' /etc/redis/redis.conf

CMD ["redis-server", "--protected-mode", "no"]
