# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM debian:bookworm as node-builder

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        nodejs \
        npm

RUN mkdir -p /app
WORKDIR /app

COPY package.json package-lock.json /app
RUN npm install

COPY ./static/js/*.coffee /app/static/js/
COPY ./static/sass/*.scss /app/static/sass/
RUN npm run coffee-prod && \
    npm run sass-prod
