# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
    nginx

RUN mkdir -p /usr/src/app
COPY ./bin/start_nginx.sh /usr/src/app/bin/start_nginx.sh
WORKDIR /usr/src/app

ENV GIT_HASH=$GIT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ENV GIT_BRANCH=$GIT_BRANCH

COPY docker/nginx/nginx.development.conf docker/nginx/nginx.production.conf /etc/nginx/sites-available
RUN rm -f /etc/nginx/sites-enabled/default

CMD ["bash", "bin/start_nginx.sh"]
