# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}
    
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libraspberrypi0 \
        libraspberrypi0 \
        libssl-dev \
        libzmq3-dev \
        libzmq5-dev \
        libzmq5 \
        lsb-release \
        mplayer \
        net-tools \
        omxplayer \
        procps \
        psmisc \
        python3-dev \
        python3-gi \
        python3-pil \
        python3-pip \
        python3-setuptools \
        python3-simplejson \
        python3-full \
        sqlite3

# Works around issue with `curl`
# https://github.com/balena-io-library/base-images/issues/562
RUN c_rehash

# We need this to ensure that the wheels can be built.
# Otherwise we get "invalid command 'bdist_wheel'"
#RUN python3 -m venv .venv \
#    source .venv/bin/activate \
#    python3 -m pip install wheel
# Keep a newline below here to not break the concatination of files.
