# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
    nginx

ENV GIT_HASH=$GIT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ENV GIT_BRANCH=$GIT_BRANCH

COPY docker/nginx/nginx.conf /etc/nginx/sites-enabled/anthias.conf

# @TODO: Find a way to generate the cert and key files ad-hoc.
COPY docker/nginx/cert.pem /etc/nginx/cert.pem
COPY docker/nginx/key.pem /etc/nginx/key.pem

RUN rm -f /etc/nginx/sites-enabled/default

CMD ["nginx", "-g", "daemon off;"]
