{% if environment == 'production' %}
FROM debian:bookworm as node-builder

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        nodejs \
        npm

RUN mkdir -p /app
WORKDIR /app

COPY package.json package-lock.json /app
RUN npm install

COPY ./static/js/*.coffee /app/static/js/
COPY ./static/sass/*.scss /app/static/sass/
RUN npm run coffee-build && \
    npm run sass-build

{% endif %}
{% include 'Dockerfile.base.j2' %}

COPY requirements/requirements.txt /tmp/requirements.txt
{% if disable_cache_mounts %}
RUN \
{% else %}
RUN --mount=type=cache,target=/root/.cache/pip \
{% endif %}
    pip3 install -r /tmp/requirements.txt --break-system-packages

RUN mkdir -p /usr/src/app
COPY . /usr/src/app/
WORKDIR /usr/src/app

{% if environment == 'production' %}
COPY --from=node-builder \
    /app/static/css/ \
    /usr/src/app/static/css/
COPY --from=node-builder \
    /app/static/js/*.js* \
    /usr/src/app/static/js/
{% endif %}

ENV GIT_HASH={{ git_hash }}
ENV GIT_SHORT_HASH={{ git_short_hash }}
ENV GIT_BRANCH={{ git_branch }}
ENV DEVICE_TYPE={{ board }}

CMD ["bash", "bin/start_server.sh"]
