FROM debian:buster

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libnss3 \
        libssl-dev \
        libzmq3-dev \
        lsb-release \
        mplayer \
        net-tools \
        procps \
        psmisc \
        python-dev \
        python-gobject \
        python-pil \
        python-pip \
        python-setuptools \
        python-simplejson \
        sqlite3 && \
    apt-get clean
