RUN --mount=type=cache,target=/var/cache/apt \
    apt-get -y install --no-install-recommends \
        dnsmasq \
        wireless-tools

WORKDIR /usr/src/app

RUN curl -sL -o /tmp/wifi_connect.tgz "$ARCHIVE_URL" && \
    tar xfz /tmp/wifi_connect.tgz -C /usr/src/app && \
    rm /tmp/wifi_connect.tgz

COPY requirements/requirements.wifi-connect.txt /tmp/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r /tmp/requirements.txt

COPY send_zmq_message.py ./

RUN touch /var/lib/misc/dnsmasq.leases

COPY bin/start_wifi_connect.sh ./

ENV GIT_HASH=$GIT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ENV GIT_BRANCH=$GIT_BRANCH

CMD ["bash", "start_wifi_connect.sh"]
