FROM balenalib/rpi-raspbian:buster as viewer-builder

RUN sed -i -e 's/#deb-src/deb-src/' /etc/apt/sources.list
RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        g++ \
        libinput-dev \
        libqt5gui5 \
        libqt5webkit5-dev \
        libqt5x11extras5-dev \
        libts-dev \
        libudev-dev \
        libxcb-xinerama0 \
        libxcb-xinerama0-dev \
        make && \
    apt-get clean

RUN mkdir /src
WORKDIR /src
COPY webview/ /src/
RUN /usr/lib/arm-linux-gnueabihf/qt5/bin/qmake
RUN make -j 4
RUN make install

FROM balenalib/rpi-raspbian:buster

RUN apt-get update && \
    apt-get -y install \
        build-essential \
        curl \
        git-core \
        gstreamer1.0-plugins-good \
        libdbus-glib-1-dev \
        libffi-dev \
        libqt5webkit5 \
        libraspberrypi0 \
        libssl-dev \
        libts-dev \
        net-tools \
        omxplayer \
        psmisc \
        python-dev \
        python-gobject \
        python-netifaces \
        python-pip \
        python-setuptools \
        sqlite3 && \
    apt-get clean

# Install Python requirements
ADD requirements/requirements.viewer.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.viewer.txt

# QtBase from packages does not support eglfs
ARG PI_VERSION=pi3
RUN curl -L \
    "https://github.com/Screenly/screenly-ose-webview/releases/download/v0.1/qtbase-$PI_VERSION.tar.gz" \
    > /tmp/qtbase.tar.gz
RUN tar -xzf /tmp/qtbase.tar.gz -C /usr/local
RUN echo "/usr/local/qt5pi/lib" > /etc/ld.so.conf.d/00-qt5pi.conf
RUN ldconfig

# Fix symlinks
RUN rm -f /usr/lib/arm-linux-gnueabihf/libEGL.so.1
RUN rm -f /usr/lib/arm-linux-gnueabihf/libEGL.so.1.0.0
RUN ln -s /opt/vc/lib/libbrcmEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so
RUN ln -s /opt/vc/lib/libbrcmEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so.1
RUN ln -s /opt/vc/lib/libbrcmEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so.1.0.0

RUN rm -f /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2
RUN rm -f /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0
RUN ln -s /opt/vc/lib/libbrcmGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so
RUN ln -s /opt/vc/lib/libbrcmGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2
RUN ln -s /opt/vc/lib/libbrcmGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0

RUN mkdir -p /usr/local/share/ScreenlyWebview
COPY --from=viewer-builder /src/ScreenlyWebview /usr/local/bin/
COPY --from=viewer-builder /src/res /usr/local/share/ScreenlyWebview/

WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app
COPY . /usr/src/app/

CMD ["bash", "./bin/start_viewer.sh"]
