FROM screenly/srly-ose-base:latest-x86

RUN apt-get -y install wget

ADD requirements/requirements.txt /tmp/requirements.txt
ADD requirements/requirements.dev.txt /tmp/requirements.dev.txt
ADD requirements/requirements.viewer.txt /tmp/requirements.viewer.txt

ARG GECKODRIVER_DL_URL="https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz"

RUN wget $GECKODRIVER_DL_URL -O /tmp/geckodriver.tar.gz

RUN pip install --no-cache-dir \
    -r /tmp/requirements.txt \
    -r /tmp/requirements.dev.txt \
    -r /tmp/requirements.viewer.txt

RUN mkdir -p /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app

ARG GIT_HASH
ENV GIT_HASH=$GIT_HASH
ARG GIT_SHORT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ARG GIT_BRANCH
ENV GIT_BRANCH=$GIT_BRANCH
