# vim: ft=dockerfile

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get -y install --no-install-recommends \
        dnsmasq \
        iw \
        network-manager \
        unzip \
        wget \
        wireless-tools

WORKDIR /usr/src/app

# @TODO: WiFi Connect 4.11.1 doesn't have a release for Raspberry Pi
#        devices that has ARMv6 support. We should remove this once a
#        new compatible release is available.
RUN if [[ ! -z "$ARCHIVE_URL" ]]; then \
    curl -sL -o /tmp/wifi_connect.zip "$ARCHIVE_URL" && \
    unzip -o /tmp/wifi_connect.zip -d /usr/src/app && \
    rm /tmp/wifi_connect.zip; fi

COPY requirements/requirements.wifi-connect.txt /tmp/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r /tmp/requirements.txt --break-system-packages

COPY send_zmq_message.py ./

RUN touch /var/lib/misc/dnsmasq.leases

COPY bin/start_wifi_connect.sh ./

ENV DEVICE_TYPE=$BOARD
ENV GIT_HASH=$GIT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ENV GIT_BRANCH=$GIT_BRANCH

CMD ["bash", "start_wifi_connect.sh"]
