# vim: ft=dockerfile

COPY requirements/requirements.txt /tmp/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
  pip3 install -r /tmp/requirements.txt

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/

ENV GIT_HASH=$GIT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ENV GIT_BRANCH=$GIT_BRANCH

CMD celery worker \
  -A server.celery \
  -B -n worker@screenly \
  --loglevel=info \
  --schedule \
  /tmp/celerybeat-schedule
