FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

RUN install_packages dnsmasq wireless-tools

WORKDIR /usr/src/app

ARG VERSION="4.4.0"
RUN curl -Ls "https://github.com/balena-io/wifi-connect/releases/download/v$VERSION/wifi-connect-v$VERSION-linux-%%BALENA_ARCH%%.tar.gz" \
  | tar -xvz -C  /usr/src/app/

RUN mkdir bin
COPY bin/start_wifi_connect.sh ./bin/

CMD ["bash", "bin/start_wifi_connect.sh"]
