FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    redis-server && \
    apt-get clean

CMD ["redis-server", "--protected-mode", "no"]
