#!/usr/bin/env bun
/**
 * Materializes a curated subset of Font Awesome SVGs from the
 * @fortawesome/fontawesome-free package into assets/images/icons/
 * so Hugo can inline them via the partials/icon.html helper.
 *
 * Mirrors scripts/install-fonts.ts in spirit — the icons live under
 * assets/ (gitignored) and are regenerated by `bun run icons:install`
 * (chained into css:build / css:watch via package.json). Adding a new
 * icon is a one-line edit to the ICONS list below; SVGs are copied
 * verbatim so the upstream FA attribution comment stays intact for
 * license compliance (CC BY 4.0).
 */
import { copyFileSync, mkdirSync, readdirSync, rmSync } from 'node:fs'
import { join } from 'node:path'

// `name` is the slug we reference from templates (and the destination
// filename). `pack` matches the FA package's directory layout under
// node_modules/@fortawesome/fontawesome-free/svgs/.
const ICONS: ReadonlyArray<{ name: string; pack: 'brands' | 'solid' }> = [
  { name: 'github', pack: 'brands' },
  { name: 'linkedin', pack: 'brands' },
  { name: 'youtube', pack: 'brands' },
  { name: 'heart', pack: 'solid' },
]

const SRC = 'node_modules/@fortawesome/fontawesome-free/svgs'
const DEST = 'assets/images/icons'

rmSync(DEST, { recursive: true, force: true })
mkdirSync(DEST, { recursive: true })

for (const icon of ICONS) {
  copyFileSync(
    join(SRC, icon.pack, `${icon.name}.svg`),
    join(DEST, `${icon.name}.svg`),
  )
}

const installed = readdirSync(DEST).length
console.log(`installed ${installed} icons → ${DEST}/`)
