from typing import Any, Iterable, overload

class PubSub:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def subscribe(self, *args: Any, **kwargs: Any) -> None: ...
    def listen(self) -> Iterable[dict[str, Any]]: ...
    def close(self) -> None: ...

# All call sites use decode_responses=True, so responses are str (not bytes).
# This stub narrows the type accordingly.
class Redis:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, name: Any) -> str | None: ...
    def set(
        self, name: Any, value: Any, *args: Any, **kwargs: Any
    ) -> bool: ...
    def expire(
        self, name: Any, time: int, *args: Any, **kwargs: Any
    ) -> bool: ...
    def publish(self, channel: Any, message: Any, **kwargs: Any) -> int: ...
    def pubsub(self, **kwargs: Any) -> PubSub: ...
    def rpush(self, name: Any, *values: Any) -> int: ...
    # Real signature is overloaded on `count`: `lpop(name)` returns a single
    # value, `lpop(name, count=N)` returns a list. Anthias only uses the
    # no-count form, so model that and don't pretend to support `count`.
    @overload
    def lpop(self, name: Any) -> str | None: ...
    @overload
    def lpop(self, name: Any, count: int) -> list[str] | None: ...
    def blpop(
        self, keys: Any, timeout: int | float | None = ...
    ) -> tuple[str, str] | None: ...
