---
- name: Configure boot partition (/boot/{config,cmdline}.txt)
  ansible.builtin.include_tasks: boot.yml
  tags:
    - touches-boot-partition
    - raspberry-pi

- name: Install/remove apt packages
  ansible.builtin.include_tasks: packages.yml

- name: Install and configure Docker
  ansible.builtin.include_tasks: docker.yml

- name: Configure /etc/timezone
  ansible.builtin.include_tasks: timezone.yml

- name: Apply distribution upgrade
  ansible.builtin.include_tasks: dist_upgrade.yml
  tags:
    - system-upgrade

- name: Miscellaneous host-level config (rc.local, dpkg, swap)
  ansible.builtin.include_tasks: misc.yml
