---
- name: Install rc.local
  ansible.builtin.template:
    src: rc.local
    dest: /etc/rc.local
    mode: "0755"
    owner: root
    group: root

- name: Install dpkg 01_nodoc filter
  ansible.builtin.copy:
    src: 01_nodoc
    dest: /etc/dpkg/dpkg.cfg.d/01_nodoc
    mode: "0644"
    owner: root
    group: root

- name: Disable swap
  ansible.builtin.command:
    cmd: /sbin/swapoff --all
    removes: /var/swap

- name: Remove swapfile from disk
  ansible.builtin.file:
    path: /var/swap
    state: absent
