from typing import Any, Callable

class AsyncWebsocketConsumer:
    channel_name: str
    channel_layer: Any
    groups: list[str]

    @classmethod
    def as_asgi(cls, **initkwargs: Any) -> Callable[..., Any]: ...
    async def connect(self) -> None: ...
    async def disconnect(self, code: int) -> None: ...
    async def accept(self, subprotocol: str | None = ...) -> None: ...
    async def send(
        self,
        text_data: str | None = ...,
        bytes_data: bytes | None = ...,
        close: bool = ...,
    ) -> None: ...
    async def close(
        self, code: int | bool = ..., reason: str | None = ...
    ) -> None: ...
