baseURL = 'https://anthias.screenly.io/'
languageCode = 'en-us'
title = "Anthias - Free Open Source Digital Signage Software"

disableKinds = ['taxonomy']

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    lineNos = false
    tabWidth = 4
    style = "github"

[menus]
  [[menus.main]]
    name = 'Features'
    pageRef = '/features'
    weight = 10
  [[menus.main]]
    name = 'Apps'
    url = 'https://signage-apps.com/?utm_source=anthias.screenly.io&utm_medium=referral&utm_campaign=nav'
    weight = 15
    [menus.main.params]
      external = true
  [[menus.main]]
    name = 'Get Started'
    pageRef = '/get-started'
    weight = 20
  [[menus.main]]
    name = 'Docs'
    pageRef = '/docs'
    weight = 25
  [[menus.main]]
    name = 'API'
    pageRef = '/api'
    weight = 30
  [[menus.main]]
    name = 'FAQ'
    pageRef = '/faq'
    weight = 40
  [[menus.main]]
    name = 'Screenly'
    url = 'https://www.screenly.io'
    weight = 50
    [menus.main.params]
      external = true

