baseURL = 'https://anthias.screenly.io/'
languageCode = 'en-us'
title = "Anthias - The world's most popular open source digital signage project"

disableKinds = ['taxonomy']

[menus]
  [[menus.main]]
    name = 'Features'
    pageRef = '/features'
    weight = 10
  [[menus.main]]
    name = 'Get Started'
    pageRef = '/get-started'
    weight = 20
  [[menus.main]]
    name = 'Docs'
    pageRef = '/docs'
    weight = 25
  [[menus.main]]
    name = 'API'
    pageRef = '/api'
    weight = 30
  [[menus.main]]
    name = 'FAQ'
    pageRef = '/faq'
    weight = 40
  [[menus.main]]
    name = 'Screenly'
    url = 'https://www.screenly.io'
    weight = 50
    [menus.main.params]
      external = true

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'static/assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'content'
    target = 'content'
