from typing import Any

class ApplicationCommunicator:
    def __init__(self, application: Any, scope: dict[str, Any]) -> None: ...
    async def wait(self, timeout: float = ...) -> None: ...
    def stop(self, exceptions: bool = ...) -> None: ...
    async def send_input(self, message: dict[str, Any]) -> None: ...
    async def receive_output(self, timeout: float = ...) -> dict[str, Any]: ...
    async def receive_nothing(
        self, timeout: float = ..., interval: float = ...
    ) -> bool: ...
