---
name: Ansible Lint

on:
  push:
    branches:
      - master
      - production
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - master
      - production
    paths:
      - 'ansible/**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "ansible/"
