name: Run JavaScript Linter and Formatter

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mjs'
      - '.github/workflows/javascript-lint.yaml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mjs'
      - '.github/workflows/javascript-lint.yaml'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.19

      - name: Install dependencies
        run: bun ci

      - name: Run ESLint
        run: bun run lint:check

      - name: Run Prettier
        run: bun run format:check
