name: Build SBOMs

on:
  push:
    branches:
      - master
    paths:
      - 'bun.lock'
      - 'uv.lock'
    tags:
      - 'v*'

jobs:
  run-tests:
    uses: ./.github/workflows/docker-test.yaml

  js-sbom:
    needs: run-tests
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build and upload SBOM
        uses: sbomify/github-action@master
        env:
          COMPONENT_ID: 'LCkvzm8qaL'
          COMPONENT_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
          LOCK_FILE: 'bun.lock'
          AUGMENT: true
          UPLOAD: true
          OUTPUT_FILE: js.cdx.json

      - name: Attest
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4
        with:
          subject-path: '${{ github.workspace }}/*.cdx.json'

  python-sbom:
    needs: run-tests
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build and upload SBOM
        uses: sbomify/github-action@master
        env:
          COMPONENT_ID: 'Vhc4zm8pdV'
          COMPONENT_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
          LOCK_FILE: 'uv.lock'
          AUGMENT: true
          UPLOAD: true
          OUTPUT_FILE: python.cdx.json

      - name: Attest
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4
        with:
          subject-path: '${{ github.workspace }}/*.cdx.json'
