name: Build SBOMs

on:
  push:
    branches:
      - master
    paths:
      - 'bun.lock'
      - 'uv.lock'

jobs:
  run-tests:
    uses: ./.github/workflows/docker-test.yaml

  js-sbom:
    needs: run-tests
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build and upload SBOM
        uses: sbomify/github-action@ac8b0d423c90447f3011ef8ab5f9ff2e854c6931 # master
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: 'LCkvzm8qaL'
          LOCK_FILE: 'bun.lock'
          AUGMENT: true
          UPLOAD: true
          OUTPUT_FILE: js.cdx.json

      - name: Attest
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4
        with:
          subject-path: '${{ github.workspace }}/*.cdx.json'

  python-sbom:
    needs: run-tests
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build and upload SBOM
        uses: sbomify/github-action@ac8b0d423c90447f3011ef8ab5f9ff2e854c6931 # master
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: 'Vhc4zm8pdV'
          LOCK_FILE: 'uv.lock'
          AUGMENT: true
          UPLOAD: true
          OUTPUT_FILE: python.cdx.json

      - name: Attest
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4
        with:
          subject-path: '${{ github.workspace }}/*.cdx.json'
